version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.28.1
    user: root
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      # - '--alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - node-exporter:node-exporter

  node-exporter:
    image: prom/node-exporter:v1.2.0
    restart: unless-stopped
    expose:
      - 9100

  cadvisor:
    image: google/cadvisor:v0.33.0
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080

  grafana:
      image: grafana/grafana:8.0.0
      user: "$UID:$GID"
      links:
        - prometheus:prometheus
      volumes:
          - ./gfdata:/var/lib/grafana
          - ./grafana/provisioning/:/etc/grafana/provisioning/
      ports:
          - 3050:3000
      restart: unless-stopped
      depends_on:
          - prometheus
      environment: 
          - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
          - GF_SMTP_ENABLED=true
          - GF_SMTP_USER=sialitech@gmail.com
          - GF_SMTP_PASSWORD=frond9_shampoo6_fidel8_0rev_Exquisite
          - GF_SMTP_HOST=smtp.gmail.com:465
          - GF_SMTP_SKIP_VERIFY=true
          - GF_SMTP_FROM_ADDRESS=sialitech@gmail.com
          - GF_RENDERING_SERVER_URL=http://renderer:8081/render
          - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
          - GF_LOG_FILTERS=rendering
          - server=node-exporter
  renderer:
    image: grafana/grafana-image-renderer:2.0.0-beta1
    ports:
        - 8081
    environment:
        - ENABLE_METRICS=true